```yaml
name: Publish Pre-Release to TestPyPI

on:
  release:
    types: [prereleased]  # triggers only for pre-releases

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: python -m pip install --upgrade build twine

      - name: Build package
        run: python -m build

      - name: Upload to TestPyPI
        run: twine upload -r testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
```
